### ISSUE TITLE
Check the pack version before building

### ISSUE THREAD

**Issue by fbiville** [projectriff/builder#30]
I had not realized until now that the build of `riff-buildpack-group` depended on the version of the locally installed `pack`. My local setup did not work until @ericbottard made me realize I was using a too outdated version of `pack`.

One thing we could do at least is to check whether we're meeting the minimal compatible `pack` version for the riff buildpack/builder to work before building anything.

**Comment by jldec** [comment]
@ericbottard @fbiville 
how about ensuring the correct pack version in the Makefile instead of depending on the local workstation pack.

**Comment by scothis** [comment]
Superseded by #46
